version: '2.17.3'

volumes:

  foodgram_database_volume:
  foodgram_media_volume:
  foodgram_static_volume:

services:

  foodgram_database:
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - foodgram_database_volume:/var/lib/postgresql/data/

  foodgram_backend:
    depends_on:
      - foodgram_database
    image: thesuncatcher222/foodgram_backend:latest
    env_file: .env
    volumes:
      - foodgram_media_volume:/foodgram/foodgram_app/media
      - foodgram_static_volume:/foodgram/foodgram_app/collected_static

  foodgram_frontend:
    image: thesuncatcher222/foodgram_frontend:latest
    env_file: .env
    volumes:
      - foodgram_static_volume:/static
    command: cp -r /app/build/. /static/

  foodgram_gateway:
    depends_on:
      - foodgram_backend
      - foodgram_frontend
    image: thesuncatcher222/foodgram_gateway:latest
    ports:
      - 8002:8000
    volumes:
      - foodgram_media_volume:/home/foodgram/media
      - foodgram_static_volume:/home/foodgram/static
