version: '2.17.3'

volumes:

  db_volume:
  media_volume:
  static_volume:

services:

  postgres_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - db_volume:/var/lib/postgresql/data/

  backend:
    depends_on:
      - postgres_db
    image: altair21817/foodgram_backend
    env_file: .env
    volumes:
      - media_volume:/foodgram/foodgram_app/media
      - static_volume:/foodgram/foodgram_app/collected_static

  frontend:
    image: altair21817/foodgram_frontend
    volumes:
      - static_volume:/static
    command: cp -r /app/build/. /static/

  nginx:
    image: altair21817/foodgram_nginx
    ports:
      - 8000:80
    volumes:
      - media_volume:/home/foodgram/media
      - static_volume:/home/foodgram/static
