FROM nginx:1.22.1-alpine
LABEL description="Foodgram gateway" \
      version="1.0" \
      maintainer="TheSuncatcher222" \
      deployer="https://github.com/TheSuncatcher222"
COPY nginx.conf /etc/nginx/templates/default.conf.template
