FROM nginx:1.22.1
LABEL description="Footgram Nginx gateway" \
      version="1.0" \
      maintainer="Altair21817" \
      deployer="https://github.com/Altair21817"
COPY nginx.conf /etc/nginx/templates/default.conf.template
